subprojects {
    dependencies { implementation project(':Editor'); implementation project(':Client') }
    tasks.register('copyJarToBin', Copy) {
        dependsOn jar
        from tasks.jar
        into project(':Editor').layout.projectDirectory.dir('plugins/inactive')
    }
    tasks.register('buildAndMove') { dependsOn 'copyJarToBin' }
}
